### ISSUE TITLE
a question about the automl.pdf

### ISSUE THREAD

**Issue by cjen07** [DenisVorotyntsev/AutoSeries#2]
Hi,

Thank you for sharing your code and ppt.
I have learned a lot from your code and analysis!

I saw "Determine important features: fit random forest -> top 3 (gini)" in your 'automl.pdf'
but I found the default lightgbm boosting params is 'gbdt' as shown here: https://lightgbm.readthedocs.io/en/latest/Parameters.html#boosting
and I found no clue in your code about random forest, and I wonder if I made any mistakes

Sincerely,
Wang Chen

**Comment by DenisVorotyntsev** [comment]
Hello, 
You are right, the presentation should contain "fit lgb -> top 3 (gain)" (lgb instead of rf and gain instead of gini) or "fit gradient boosting -> top 3 (gain)". I'm not sure why I decided to write "rf+gini" instead of correct version. However, commonly there is no big difference in the most important features between determined using lgb+gain or rf+gini importance.

**Comment by cjen07** [comment]
Got it, thanks again : D
